### ISSUE TITLE
How to let the suggestion list on the center position?

### ISSUE THREAD

**Issue by NeoLSN** [fayeed/flutter_mentions#10]
If there is any other UI aside, the portal will be tilting.
Could you let the suggestion list always be on the screen center?
![image](https://user-images.githubusercontent.com/5782106/93715342-49824c00-fb9b-11ea-81cd-954e1438f56c.png)

**Comment by fayeed** [comment]
@NeoLSN Thanks for reporting the issue I will take a look.

**Comment by fayeed** [comment]
@NeoLSN Can you share the code I just tried reproducing this & everything works fine
![Simulator Screen Shot - iPhone X - 2020-09-28 at 11 52 18](https://user-images.githubusercontent.com/8464270/94397262-146c8f80-0181-11eb-9c79-3d12ba4837c0.png)

**Comment by NeoLSN** [comment]
You need to add another UI on the left or right side of the FlutterMention.

**Comment by fayeed** [comment]
Yeah i did as you can see from the image  there are two container one on the left and another on the right which both take about 20.0 width and everything works fine on my end.

**Comment by NeoLSN** [comment]
> Yeah i did as you can see from the image there are two container one on the left and another on the right which both take about 20.0 width and everything works fine on my end.

Can you just do it on one side only?

**Comment by fayeed** [comment]
@NeoLSN so what I did is I have added two new properties called `leading` & `trailing` both are `List<Widget>`, this should do the trick.

**Comment by fayeed** [comment]
Also closing the issue.

**Comment by NeoLSN** [comment]
@fayeed What do you mean? That's just means I can't add other UI aside FlutterMentions...

**Comment by fayeed** [comment]
@NeoLSN and what is the real issue?

**Comment by NeoLSN** [comment]
I want to add a button right on the FlutterMentions like bellow codes,
```dart
Row(
  children: [
   Flexible(FlutterMentions()),
  SendButton(),
  ]
)
```
But the suggestion list will be out of the screen. That's the issue.

**Comment by fayeed** [comment]
Yeah, and you can do that using the `trailing` widget.

**Comment by NeoLSN** [comment]
OK, I see.

**Comment by fayeed** [comment]
Also before commenting on implementation as just a "trick", please take a look at it and try using it.

**Comment by NeoLSN** [comment]
> Also before commenting on implementation as just a "trick", please take a look at it and try using it.

Yeah, I apologize about this.
