### ISSUE TITLE
Provide a way to customize markup text

### ISSUE THREAD

**Issue by NeoLSN** [fayeed/flutter_mentions#11]
We need a way to build our own markup text because we'll need to recognize those markups in the [flutter_parsed_text](https://pub.dev/packages/flutter_parsed_text) widget.

**Comment by fayeed** [comment]
I could think of two ways to this the first way is to provide a function something like this:

```dart
markupBuilder({String trigger, String mention, String: value}) String;
```

or maybe a simple string that needs to have some keywords which I can then replace with their respective values in `FlutterMentions`

Something like this for this, where `[trigger]` will get replaced by the current mention trigger & so on: 

```dart
makup: '[trigger][mention][value]'
```

**Comment by NeoLSN** [comment]
Personally, I prefer the first one, too.
But I think if you can achieve both ways, you could set a priority orders for these.
