### ISSUE TITLE
Rich Text Editing

### ISSUE THREAD

**Issue by JEuler** [fayeed/flutter_mentions#12]
Hi! Great stuff! Do you have plans to support basic RichText editing like adding bold or etc to you plugin? Can I try to like an integrate your code to the existing Zefyr? https://pub.dev/packages/zefyr

**Comment by fayeed** [comment]
@JEuler Right now I don't plan on adding basic RichText editing features, although it is possible to this in the current implementation might need a fair bit of refactoring of code.

Also, can you explain what do mean by your second question in more detail.
>Can I try to like an integrate your code to the existing Zefyr?

**Comment by JEuler** [comment]
Hm, I don't know exactly :D Just looking for some rich text editor with mention functionality. 
Maybe I will try to work with your repository and enhance it with richness like bold or italic. Will see.
