### ISSUE TITLE
Clear text field

### ISSUE THREAD

**Issue by JEuler** [fayeed/flutter_mentions#13]
How I can clear text field after onEditingComplete callback? Setting `defaultText` not working

**Comment by fayeed** [comment]
You could just set a `key` for the `FlutterMention` widget & then just these two ways to clear the field.

1. Using the controller's clear method:
`key.currentState.controller.clear();`

2. Using the controller's text property:
`key.currentState.controller.text = '';`

**Comment by JEuler** [comment]
Thank you very much!

**Comment by zzterrozz** [comment]
@fayeed 

Bringing the key in the parent widget creates me this error:
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
Multiple widgets used the same GlobalKey.
```

How can we please access the `key` from a different widget ?

**Comment by zzterrozz** [comment]
@fayeed

Bringing the key in the parent widget creates me this error:

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
Multiple widgets used the same GlobalKey.

How can we please access the `key` from a different widget ?

**Comment by dorutInventiff** [comment]
How can I access the text giving the fact there is no controller parameter in the FlutterMentions? Like I want to assign a TextEditingController to the FlutterMentions. How can I do that with the key prop?
