### ISSUE TITLE
onMarkupChanged and onMentionAdd

### ISSUE THREAD

**Issue by JEuler** [fayeed/flutter_mentions#15]
Hi! I'm processing the data (layouting it with html tags) in onMarkupChanged. But I see, that if I'm not typing anything rather than just @ mention the data in onMarkupChanged callback is wrong and contains only @. But If typed anything than all is okay. 

![2020-09-29_13-39-52](https://user-images.githubusercontent.com/231950/94548409-56690480-0259-11eb-848d-29c6157b27ea.png)
![2020-09-29_13-40-03](https://user-images.githubusercontent.com/231950/94548410-58cb5e80-0259-11eb-9e29-7fe60b57b2a8.png)
![2020-09-29_13-40-46](https://user-images.githubusercontent.com/231950/94548432-64b72080-0259-11eb-8ded-44a54ccf06bb.png)

What I can do to enable mentions callback firing in case I'm just entering only mention?

**Comment by JEuler** [comment]
It is the same if I'm entering two mentions in row. 
![2020-09-29_13-42-12](https://user-images.githubusercontent.com/231950/94548580-9c25cd00-0259-11eb-830c-8c41b96fa186.png)
![2020-09-29_13-42-18](https://user-images.githubusercontent.com/231950/94548586-9def9080-0259-11eb-9b5a-2caf3aeba62e.png)

**Comment by fayeed** [comment]
@JEuler I don't understand exactly can you explain in more detail that would be great!

**Comment by JEuler** [comment]
Hi! I meant that when you tap on Suggestion (Mention) the `onMarkupChanged` is not firing and nothing is added to the `rawComment` variable I'm defining. So, the problem is that: onMarkupChanged callback is not firing in case we are tapping on the suggestion and it is added to textfield.

**Comment by JEuler** [comment]
Is that clear now? :)

**Comment by fayeed** [comment]
Ahh Yes, I will take a look at it, Thanks for the clarification.

**Comment by JEuler** [comment]
Did you have any chance to look? :)

**Comment by fayeed** [comment]
@JEuler Gonna look at today

**Comment by JEuler** [comment]
@fayeed Thank you very very much! 🤗

**Comment by fayeed** [comment]
@JEuler fixed in v1.0.2

**Comment by JEuler** [comment]
Insanely cool! Thanks! 🤗
