### ISSUE TITLE
type 'Mention' is not a subtype of type 'bool' after flutter 1.22.0 upgrade

### ISSUE THREAD

**Issue by krishnakumarcn** [fayeed/flutter_mentions#19]
The following _TypeError was thrown while handling a gesture:
type 'Mention' is not a subtype of type 'bool'

When the exception was thrown, this was the stack: 
#0      FlutterMentionsState.addMention (package:flutter_mentions/src/mention_view.dart:292:24)
#1      FlutterMentionsState.build.<anonymous closure> (package:flutter_mentions/src/mention_view.dart:393:19)
#2      OptionList.build.<anonymous closure>.<anonymous closure> (package:flutter_mentions/src/option_list.dart:38:26)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)

**Comment by krishnakumarcn** [comment]
This can be reproduced from the example project by.
Type @ -> Select any mention items.

**Comment by fayeed** [comment]
@krishnakumarcn fixed in 1.0.2
