### ISSUE TITLE
Crashes when we use Special characters in display name

### ISSUE THREAD

**Issue by nirajjoshi** [fayeed/flutter_mentions#20]
@fayeed 
Tried to use Example application itself with display name **~|[]{}#%^*+=_\|<>\$£€•.,?!**.

App throws exception like: **_Nothing to repeat(@~|[]{}#%^*+=_|<>$£€•.,?!|@khaled|@markT|@JhonL|#([A-Za-z0-9])*|#reactjs|#javascript)_**

Please refer screenshots for more reference:

<img width="1206" alt="Screenshot 2020-10-12 at 1 08 32 PM" src="https://user-images.githubusercontent.com/4289654/95718656-5ff86080-0c8c-11eb-84d9-d1f91b20fb3e.png">

<img width="1206" alt="Screenshot 2020-10-12 at 12 48 09 PM" src="https://user-images.githubusercontent.com/4289654/95718819-96ce7680-0c8c-11eb-8a74-fc11dacb6743.png">

<img width="1206" alt="Screenshot 2020-10-12 at 12 48 53 PM" src="https://user-images.githubusercontent.com/4289654/95718976-d4cb9a80-0c8c-11eb-9b20-9dbf893c74ef.png">

**Comment by JEuler** [comment]
Yeah, same problem! Any solutions other than just clean special characters? :)

**Comment by fayeed** [comment]
I think this might be because there is no functionality to escape special characters that could be used in the string like `$`, `|`, etc. Do note, that most symbols should work except a few like `|` which is used as a separator in Regex. If any of you guys can create PR to fix this that would be great, I will eventually fix this but cannot tell when.

**Comment by fayeed** [comment]
You should also check issue #5 to learn more.

**Comment by JEuler** [comment]
So, you suggest to convert all used strings in lib to the raw strings, correct?

**Comment by fayeed** [comment]
@JEuler @nirajjoshi Should be fixed in v1.0.10.

**Comment by nirajjoshi** [comment]
> @JEuler @nirajjoshi Should be fixed in v1.0.10.

Thanks.
