### ISSUE TITLE
HTML tags

### ISSUE THREAD

**Issue by JEuler** [fayeed/flutter_mentions#21]
Hi! Is there an easy way to render HTML tags inside your editor?

**Comment by fayeed** [comment]
@JEuler can you elaborate more?

**Comment by JEuler** [comment]
Okay, but a bit later. Thx.

**Comment by JEuler** [comment]
So, basically, I want to be able to render HTML tags within your text editor. So, If I'm facing text with <strong>Hello</strong>, it will be rendered as HTML text. I'm using this https://pub.dev/packages/flutter_html package to render HTML. 

As I understand this is a very complex topic and I should address it by using some kind of RichText editor, like mentioned Zefyr. 

Feel free to close. :)
