### ISSUE TITLE
Access the GlobalKey<FlutterMentionsState> outside of the widget

### ISSUE THREAD

**Issue by zzterrozz** [fayeed/flutter_mentions#22]
Hi @fayeed,

How can I access the `GlobalKey<FlutterMentionsState> _textFormFieldKey = GlobalKey<FlutterMentionsState>();` outside of the widget please ?

I would like to give the key a `TextEditingController` value when initiated & be able to `clear()` its value.

**Comment by fayeed** [comment]
Check issue #13.
