### ISSUE TITLE
How to run example

### ISSUE THREAD

**Issue by bartonhammond** [fayeed/flutter_mentions#28]
I did 
*  flutter create .
*  flutter run

now what? 

![Screen Shot 2020-11-02 at 8 15 43 AM](https://user-images.githubusercontent.com/1282364/97878007-ab2dee00-1ce3-11eb-864b-b295202ed301.png)

**Comment by fayeed** [comment]
That's it there a TextField below the Get Text Button, you can type some mentions there using `@` and then later press the button to log the markup text.

**Comment by bartonhammond** [comment]
Ok - thanks
might be worth putting a border around the text field.
