### ISSUE TITLE
Should able to give end position to suggestionBuilder.for TextInputType multiline.

### ISSUE THREAD

**Issue by sneha-solutelabs** [fayeed/flutter_mentions#34]
while using TextInputType multiline and open keyboard. keyboard overlaps with suggestion list. when keyboard opens it should end top of keyboard. 
<img width="309" alt="Screenshot 2020-12-14 at 11 13 48 AM" src="https://user-images.githubusercontent.com/72002256/102045435-14367480-3dff-11eb-934e-3406f5acad1c.png">

**Comment by fayeed** [comment]
@sneha-solutelabs you can disable the default suggestion list and write your own custom list to handle any behavior.
