### ISSUE TITLE
Cursor position always show at the start when add new mentions into textfield

### ISSUE THREAD

**Issue by Barry0501** [fayeed/flutter_mentions#38]
Hi, your package is awesome. Android works perfectly but in IOS, it doesn't work as expected

https://user-images.githubusercontent.com/34902237/106765508-72e3d600-666b-11eb-8059-baa0ea28b0d7.mov

**Comment by dmba** [comment]
@Barry0501 why was this issue closed without PR merged? Do you know a way to solve it? I am experiencing same issue.

**Comment by Barry0501** [comment]
@dmba Yeah I figured out how to solve it. Let me create PR for this issue

**Comment by dmba** [comment]
@Barry0501 awesome, thank you
