### ISSUE TITLE
AnnotationEditingController crash when upgrade to flutter 2

### ISSUE THREAD

**Issue by letungcntt** [fayeed/flutter_mentions#44]
I can't build my app because this error :
`../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mentions-2.0.0-nullsafety/lib/src/annotation_editing_controller.dart:58:12: Error: The method 'AnnotationEditingController.buildTextSpan' has fewer named arguments than those of overridden method 'TextEditingController.buildTextSpan'.
  TextSpan buildTextSpan({TextStyle? style, bool? withComposing}) {
           ^
../../flutter/packages/flutter/lib/src/widgets/editable_text.dart:192:12: Context: This is the overridden method ('buildTextSpan').
  TextSpan buildTextSpan({required BuildContext context, TextStyle? style , required bool withComposing}) {
           ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mentions-2.0.0-nullsafety/lib/src/annotation_editing_controller.dart:58:12: Error: The method 'AnnotationEditingController.buildTextSpan' doesn't have the named parameter 'context' of overridden method 'TextEditingController.buildTextSpan'.
  TextSpan buildTextSpan({TextStyle? style, bool? withComposing}) {
           ^
../../flutter/packages/flutter/lib/src/widgets/editable_text.dart:192:12: Context: This is the overridden method ('buildTextSpan').
  TextSpan buildTextSpan({required BuildContext context, TextStyle? style , required bool withComposing}) {`

**Comment by zzterrozz** [comment]
Having the same issue, did you find a solution ?

**Comment by zzterrozz** [comment]
@letungcntt  Having the same issue, did you find a solution ?

**Comment by zzterrozz** [comment]
> yes, t have a solution but you need fork this Project

Sure, please let me know what to change in the fork!

**Comment by letungcntt** [comment]
> > yes, t have a solution but you need fork this Project
> 
> Sure, please let me know what to change in the fork!

pls check

**Comment by zzterrozz** [comment]
> yes, t have a solution but you need fork this Project
> because, if upgrade to flutter channel Master, `buildTextSpan(context, a, b)` but with master `buildTextSpan(a, b)`

I will try that
Thank you for your help and reactivity!

**Comment by zzterrozz** [comment]
> yes, t have a solution but you need fork this Project
> because, if upgrade to flutter channel Master, `buildTextSpan(context, a, b)` but with global `buildTextSpan(a, b)`

In `flutter_mentions: ^2.0.0-nullsafety` 

In `annotation_editing_controller.dart` I already have : 
```
TextSpan buildTextSpan({TextStyle? style, bool? withComposing}) {...}
```

I see in your fork that you also have kep the same code [https://github.com/letungcntt/flutter_mentions/blob/master/lib/src/annotation_editing_controller.dart](url)

Did you stay on `flutter channel master` ?

**Comment by zzterrozz** [comment]
@letungcntt 

On `channel master`, is it correct to have `TextSpan buildTextSpan({TextStyle? style, bool? withComposing}) {...}` ?

**Comment by letungcntt** [comment]
@zzterrozz on `channel master` they using `TextSpan buildTextSpan({required BuildContext context, TextStyle? style , required bool withComposing}) {` but pub-get with stable

**Comment by zzterrozz** [comment]
@letungcntt I just switched back to `flutter channel stable` to fix it for the moment
Thank you for your help

**Comment by gadearaujo** [comment]
> flutter channel stable

Unfortunately it didn't work for me, any other suggestions?

**Comment by letungcntt** [comment]
> > flutter channel stable
> 
> Unfortunately it didn't work for me, any other suggestions?

Stable version ?
