### ISSUE TITLE
Cursor moves to first position after adding a space after a mention call

### ISSUE THREAD

**Issue by sarthak290** [fayeed/flutter_mentions#6]
Hello , The error is whenever I click a space after mentioning a name like @abc the cursor moves automatically to first position that is to the starting of text field.
Please reply with a solution.

**Comment by krishnakumarcn** [comment]
In my case cursor moving to the first position after selecting a mentioned item from the list.
this happens only on android. On ios its working fine.


Any updates on this issue?

**Comment by sarthak290** [comment]
@krishnakumarcn yes same happen with me

**Comment by krishnakumarcn** [comment]
Created a PR for resolving this issue. [#8 ](https://github.com/fayeed/flutter_mentions/pull/8)

**Comment by fayeed** [comment]
I just published a new version for the package `0.1.2`, thanks @krishnakumarcn for the PR, I will close this issue.

**Comment by Abacaxi-Nelson** [comment]
Hi @fayeed @krishnakumarcn @sarthak290 
Is the issue corrected on your side ?
installing last version still move cursor at beginning.

thx, Nelson
