### ISSUE TITLE
Mention not working when data load from server

### ISSUE THREAD

**Issue by Gursewak-Uppal** [fayeed/flutter_mentions#7]
I used this plugin with Firebase and load user data (id, display name,avatar etc.)  from Firebase and set State every time when record added to list but mention not working when i selected user from list.

**Comment by fayeed** [comment]
@Gursewak-Uppal The problem is the package doesn't support Streams & once the data is passed to `FlutterMention` it doesn't change later, the reason it behaves this way was for my use-case I had all user you can mention at the start. I do plan to add this functionality later but cannot give a date.
